// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wevo.Dados.Contextos;

namespace Wevo.Dados.Migrations
{
    [DbContext(typeof(EfContext))]
    partial class EfContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wevo.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("DataNascimento")
                        .HasColumnType("date");

                    b.Property<int>("Sexo");

                    b.HasKey("Id");

                    b.ToTable("Cliente","dbo");
                });

            modelBuilder.Entity("Wevo.Dominio.Entidades.Cliente", b =>
                {
                    b.OwnsOne("Wevo.Dominio.ObjetosDeValor.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnName("Cpf")
                                .HasColumnType("char(11)");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Cliente","dbo");

                            b1.HasOne("Wevo.Dominio.Entidades.Cliente")
                                .WithOne("Cpf")
                                .HasForeignKey("Wevo.Dominio.ObjetosDeValor.Cpf", "ClienteId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Wevo.Dominio.ObjetosDeValor.Email", "Email", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnName("Email")
                                .HasColumnType("varchar(150)");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Cliente","dbo");

                            b1.HasOne("Wevo.Dominio.Entidades.Cliente")
                                .WithOne("Email")
                                .HasForeignKey("Wevo.Dominio.ObjetosDeValor.Email", "ClienteId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Wevo.Dominio.ObjetosDeValor.Nome", "Nome", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasColumnName("Nome")
                                .HasColumnType("varchar(100)");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Cliente","dbo");

                            b1.HasOne("Wevo.Dominio.Entidades.Cliente")
                                .WithOne("Nome")
                                .HasForeignKey("Wevo.Dominio.ObjetosDeValor.Nome", "ClienteId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Wevo.Dominio.ObjetosDeValor.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnName("Telefone")
                                .HasColumnType("char(11)");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Cliente","dbo");

                            b1.HasOne("Wevo.Dominio.Entidades.Cliente")
                                .WithOne("Telefone")
                                .HasForeignKey("Wevo.Dominio.ObjetosDeValor.Telefone", "ClienteId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
